services:
  postgres-db:
    image: postgres:16-alpine
    container_name: clickandeat-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clickandeat_db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: